version: '3.8'

services:
  wordpress:
    image: wordpress:php8.2-apache
    container_name: wordpress
    ports:
      - "8080:80"  
    environment:
      APACHE_SERVER_NAME: discord.yusuf-kahya.com
      WORDPRESS_DB_HOST: mysql_wp
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: mysql_wp
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wp_network
    depends_on:
      - mysql_wp

  mysql_wp:
    image: mariadb:latest
    container_name: mysql_wp
    environment:
      MYSQL_DATABASE: mysql_wp
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
      MYSQL_ROOT_PASSWORD: rootpassword
      TZ: ${TIMEZONE}  # Zeitzone hinzufügen
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"  # Port für externe Verbindungen
    networks:
      - wp_network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  discord-bot:
    build: ./discord-bot
    container_name: discord-bot
    depends_on:
      - mysql_wp  # Abhängigkeit von MySQL statt PostgreSQL
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - MYSQL_HOST=mysql_wp
      - MYSQL_PORT=3306
      - MYSQL_USER=wpuser
      - MYSQL_PASSWORD=wppassword
      - MYSQL_DATABASE=mysql_wp
      - DATABASE_URL=mysql://wpuser:wppassword@mysql_wp:3306/mysql_wp
      - TZ=${TIMEZONE}
      - API_KEY=${API_KEY}
    networks:
      - wp_network  # Gleiches Netzwerk wie MySQL
    restart: always

  web-interface:
    build: ./web-interface
    container_name: web-interface
    depends_on:
      - mysql_wp  # Auf MySQL umstellen wenn nötig
    environment:
      - DATABASE_URL=mysql://wpuser:wppassword@mysql_wp:3306/mysql_wp
      - TZ=${TIMEZONE}
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - wp_network
    restart: always

volumes:
  wordpress_data:
  db_data:

networks:
  wp_network: