services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notesdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
  discord-bot:
    build: ./discord-bot
    container_name: discord-bot
    depends_on:
      - postgres-db
    environment:
      - DISCORD_TOKEN=MTM1MTE1MjQ5ODk2NjI2NTg5Ng.GUzsLf.14bazwkuNM8ilPYlhj_zigTkF3LwDiyguWokoI
      - DATABASE_URL=postgresql://user:password@postgres-db:5432/notesdb
    restart: always

  web-interface:
    build: ./web-interface
    container_name: web-interface
    depends_on:
      - postgres-db
    environment:
      - DATABASE_URL=postgresql://user:password@postgres-db:5432/notesdb
    ports:
      - "187:187"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    restart: always

volumes:
  postgres_data:
